const test = require("node:test");
const assert = require("node:assert/strict");
const core = require("./rhai-live-core.js");

test("parses simple fn pipeline", function () {
    const result = core.parseRhaiDiagram("fn ingest() -> classify\nfn classify() -> commit\n");
    assert.equal(result.graph.nodes.size, 3);
    assert.equal(result.graph.edges.length, 2);
    assert.equal(result.diagnostics.length, 0);
});

test("emits diagnostics for unsupported and malformed lines", function () {
    const src = [
        "let x = 1",
        "fn bad_syntax() => nope",
        "if confidence > 0.8 -> commit",
    ].join("\n");
    const result = core.parseRhaiDiagram(src);
    assert.equal(result.graph.edges.length, 1);
    assert.ok(result.diagnostics.length >= 2);
    assert.ok(result.diagnostics.some((d) => d.kind === "info"));
    assert.ok(result.diagnostics.some((d) => d.kind === "error"));
});

test("builds threshold chain with false branch", function () {
    const src = "if confidence > 0.5 -> review\nif confidence > 0.8 -> commit\n";
    const result = core.parseRhaiDiagram(src);
    const mermaid = core.graphToMermaid(result.graph);
    assert.ok(mermaid.includes('|"false"|'));
    assert.ok(mermaid.includes("commit"));
    assert.ok(mermaid.includes("review"));
});

test("builds single match node with labeled outgoing arms", function () {
    const src = [
        "match result.disposition => Disposition::Unrecoverable -> halt_pipeline",
        "match result.disposition => Disposition::Recoverable -> repair_and_retry",
        "match result.disposition => Disposition::Advisory -> record_note",
    ].join("\n");
    const { graph, diagnostics } = core.parseRhaiDiagram(src);
    const mermaid = core.graphToMermaid(graph);

    assert.equal(diagnostics.length, 0);
    assert.equal(
        Array.from(graph.nodes.values()).filter((node) => node.kind === "match").length,
        1
    );
    assert.ok(mermaid.includes('match_result_disposition{"match result.disposition"}'));
    assert.ok(mermaid.includes('|"Disposition::Recoverable"|repair_and_retry'));
});

test("builds deterministic isometric layout metadata", function () {
    const src = [
        "fn ingest() -> validate",
        "fn validate() -> classify",
        "if confidence > 0.8 -> commit",
        "if confidence > 0.5 -> review",
        "fn classify() -> reconcile",
        "fn reconcile() -> commit",
    ].join("\n");
    const { graph } = core.parseRhaiDiagram(src);
    const scene = core.buildVisualizationModel(graph);

    assert.equal(scene.nodes.length, graph.nodes.size);
    assert.equal(scene.edges.length, graph.edges.length);

    const byId = new Map(scene.nodes.map((node) => [node.id, node]));
    assert.ok(byId.get("ingest").screen.x < byId.get("validate").screen.x);
    assert.ok(byId.get("validate").screen.x < byId.get("classify").screen.x);
    assert.equal(byId.get("confidence_gt_0_8").semanticType, "decision");
    assert.match(byId.get("commit").modelUri, /^data:model\/gltf\+json;base64,/);

    const encoded = byId.get("commit").modelUri.split(",")[1];
    const parsed = JSON.parse(Buffer.from(encoded, "base64").toString("utf8"));
    assert.equal(parsed.asset.version, "2.0");
    assert.equal(parsed.meshes[0].primitives[0].extras.autogenerated, true);
});

test("renders isometric svg with animated node movement on refresh", function () {
    const first = core.parseRhaiDiagram("fn ingest() -> classify\nfn classify() -> commit\n");
    const second = core.parseRhaiDiagram(
        "fn ingest() -> validate\nfn validate() -> classify\nfn classify() -> commit\n"
    );
    const firstScene = core.buildVisualizationModel(first.graph);
    const secondScene = core.buildVisualizationModel(second.graph);
    const svg = core.sceneToIsometricSvg(secondScene, firstScene);

    assert.ok(svg.includes("rhai-isometric-scene"));
    assert.ok(svg.includes("animateTransform"));
    assert.ok(svg.includes("data-model-uri="));
    assert.ok(svg.includes("validate"));
});

test("isometric scene sizes edge labels for match arms", function () {
    const { graph } = core.parseRhaiDiagram(
        "match result.disposition => Disposition::Unrecoverable -> halt_pipeline\n" +
            "match result.disposition => Disposition::Recoverable -> repair_and_retry\n"
    );
    const scene = core.buildVisualizationModel(graph);
    const svg = core.sceneToIsometricSvg(scene);
    assert.ok(svg.includes("Disposition::Unrecoverable"));
    assert.ok(/width=\"1[0-9]{2}\.[0-9]\"/.test(svg));
});

test("isometric layout gives match arms stable lanes and centers simple rejoins", function () {
    const { graph } = core.parseRhaiDiagram(
        [
            "match result.disposition => Disposition::Unrecoverable -> halt_pipeline",
            "match result.disposition => Disposition::Recoverable -> repair_and_retry",
            "match result.disposition => _ -> record_note",
            "fn repair_and_retry() -> requeue_validation",
            "fn record_note() -> requeue_validation",
        ].join("\n")
    );
    const scene = core.buildVisualizationModel(graph);
    const byId = new Map(scene.nodes.map((node) => [node.id, node]));

    const matchNode = byId.get("match_result_disposition");
    const halt = byId.get("halt_pipeline");
    const repair = byId.get("repair_and_retry");
    const defaultArm = byId.get("record_note");
    const rejoin = byId.get("requeue_validation");

    assert.equal(halt.z, matchNode.z);
    assert.equal(repair.z, matchNode.z + scene.settings.laneGap);
    assert.equal(defaultArm.z, matchNode.z + scene.settings.laneGap * 2);
    assert.ok(rejoin.x > defaultArm.x);
    assert.equal(rejoin.z, matchNode.z);
});

test("render failure guidance points mermaid users to isometric fallback", function () {
    const failure = core.buildRenderFailure(new Error("window.mermaid missing"), "mermaid-2d");
    assert.match(failure.title, /Mermaid render failed/);
    assert.match(failure.hint, /Switch to isometric-3d/);
    assert.match(failure.detail, /window\.mermaid missing/);
});
