param()

$ErrorActionPreference = "Stop"
$env:PATH = "C:\Users\wendy\.cargo\bin;C:\msys64\mingw64\bin;" + $env:PATH
Set-Location "D:\Projects\l3dg3rr"

# Pre-flight check
Write-Host "[preflight] checking cargo-tauri..."
$tauriVer = cargo tauri --version 2>$null
if (-not $tauriVer) {
    Write-Host "ERROR: cargo-tauri not installed. Run: cargo install tauri-cli --version '^2'"
    exit 1
}
Write-Host "  found $tauriVer"
$versionLine = $tauriVer | Select-String -Pattern "[\d\.]+"
$tauriSemver = $versionLine.Matches.Value

# Build
Write-Host "[1/2] building ledgrrr..."
$prevErrorAction = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$buildOutput = cargo tauri build --bundles msi 2>&1
$ErrorActionPreference = $prevErrorAction
$buildOutput | ForEach-Object { Write-Host "  $_" }
if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) { throw "tauri build failed (exit $LASTEXITCODE)" }

# Locate the output binary
$binary = Get-Item "D:\Projects\l3dg3rr\target\release\ledgrrr.exe" -ErrorAction SilentlyContinue
if (-not $binary) {
    $binary = Get-ChildItem "D:\Projects\l3dg3rr\target\release" -Recurse -Filter "ledgrrr.exe" | Select-Object -First 1
}
if (-not $binary) { throw "binary not found after build" }

# Generate hash
Write-Host "[2/2] signing binary..."
$hash = if (Get-Command b3sum -ErrorAction SilentlyContinue) {
    b3sum --raw $binary.FullName 2>$null
} else {
    $stream = [System.IO.File]::OpenRead($binary.FullName)
    $hashBytes = [System.Security.Cryptography.SHA256]::Create().ComputeHash($stream)
    $stream.Close()
    $hashStr = [System.BitConverter]::ToString($hashBytes) -replace "-", ""
    Write-Host "  (SHA256 fallback -- install b3sum for blake3)"
    $hashStr
}
if (-not $hash) { throw "hash generation failed" }

# Write datum TOML
$datumDir = "D:\Projects\l3dg3rr\.b00t\datums"
$null = New-Item -ItemType Directory -Path $datumDir -Force
$datumPath = Join-Path $datumDir "ledgrrr.toml"
$sizeKb = [math]::Round($binary.Length / 1KB, 1)

@"
# ledgrrr datum -- auto-generated by scripts/tauri-build.ps1
[datum]
name = "ledgrrr"
version = "$tauriSemver"
kind = "binary"

[build]
cargo_profile = "release"
bundle_format = "msi"

[artifact]
path = "$($binary.FullName)"
sha256 = "$hash"
size_kb = $sizeKb
"@ | Out-File -Encoding utf8 $datumPath

# Install the MSI
$msiPath = "D:\Projects\l3dg3rr\target\release\bundle\msi\ledgrrr_1.8.0_x64_en-US.msi"
if (Test-Path $msiPath) {
    Write-Host "[3/3] installing MSI..."
    $log = "$env:TEMP\l3dg3rr-install.log"
    $proc = Start-Process msiexec -Verb RunAs -ArgumentList "/i `"$msiPath`" /quiet /norestart /log `"$log`"" -Wait -PassThru
    if ($proc.ExitCode -eq 0) {
        Write-Host "  installation successful (exit code 0)"
    } else {
        Write-Host "  installation returned exit code $($proc.ExitCode)"
        if (Test-Path $log) { Get-Content $log -Tail 5 | ForEach-Object { Write-Host "    $_" } }
    }
}

# Summary
Write-Host ""
Write-Host "Build complete."
Write-Host "  binary: $($binary.FullName)  ($sizeKb KB)"
Write-Host "  hash:   $hash"
Write-Host "  datum:  $datumPath"
